name: Test Deployment
on:
  deployment_status:

permissions: read-all

jobs:
  e2eTests:
    if:
      github.repository == 'anuraghazra/github-readme-stats' &&
      github.event_name == 'deployment_status' &&
      github.event.deployment_status.state == 'success'
    name: Perform 2e2 tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run end-to-end tests.
        run: npm run test:e2e
        env:
          VERCEL_PREVIEW_URL: ${{ github.event.deployment_status.target_url }}
