name: Test Deployment
on:
  deployment_status:

permissions: read-all

jobs:
  e2eTests:
    if:
      github.repository == 'anuraghazra/github-readme-stats' &&
      github.event_name == 'deployment_status' &&
      github.event.deployment_status.state == 'success'
    name: Perform 2e2 tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run end-to-end tests.
        run: npm run test:e2e
        env:
          VERCEL_PREVIEW_URL: ${{ github.event.deployment_status.target_url }}
