name: Theme preview

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master
    paths:
      - "themes/index.js"

jobs:
  previewTheme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    name: Install & Preview

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - run: npm run preview-theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
